#! /usr/bin/env python3

import os

from lib.run_program import run_program

run_program(
    ['min', '--disable-smooth-scrolling'],
    ['librewolf'],
    ['firefox', '-P', 'default-release'],
    [
        'chromium', # doesn't seem to be able to block ads properly on youtube (as of 2023-12-18)
        '--disable-smooth-scrolling',
        '--user-data-dir=' + os.path.expanduser("~/.config/my-chromium-profiles/default"),
        '-no-default-browser-check',
    ],
)

# 
# #! /usr/bin/env bash
# 
# (librewolf --version && (librewolf $@ ; exit $?)) ||
# (firefox --version && (firefox -P default-release $@ ; exit $?))
# # on ubuntu it seems to be called `default` (not sure, can't double-check)
# # on arch it's called `default-release`
