#! /usr/bin/env python3

from lib.run_program import run_program

run_program(
    ['/usr/lib/jvm/java-21-openjdk/bin/java'], # arch
    #['/usr/lib/jvm/java-21-openjdk-amd64/bin/java'], # mint # TODO untested
)
