#! /usr/bin/env bash

# I used to use this on arch
#
# if xkblayout-state print "%s" ; then
	# echo
# else
	# i3-nagbar -t warning -m 'missing command [xkblayout-state] [paru xkblayout-state]'
	# echo 'ERR'
# fi

# now I use this on fedora 41
xkb-switch
