#! /usr/bin/env python3

import psutil
import os

GIGABYTE = 1024 * 1024 * 1024 # in bytes
ZFS_ARCSTATS = '/proc/spl/kstat/zfs/arcstats'

mem = psutil.virtual_memory()
mem = mem.available # in bytes

# ZFS
zmem = None
if os.path.isfile(ZFS_ARCSTATS):
	with open(ZFS_ARCSTATS, 'r') as f:
		for line in f.readlines():
			# c is the target size of the ARC in bytes
			# c_max is the maximum size of the ARC in bytes
			# size is the current size of the ARC in bytes
			if line.startswith('size '):
				line = line.split(' ')
				zmem = line[-1]
				zmem = int(zmem) # in bytes
				break

pmem = f'{mem / GIGABYTE:.3}G'

pzmem = ''
if zmem != None:
	zmem = mem + zmem
	pzmem += f' {zmem / GIGABYTE:.3}G'

print(pmem + pzmem)
