#! /usr/bin/env python3

from lib.run_program import run_program

run_program(
    ['ghostty'],
    ['xfce4-terminal'],
    ['wezterm'],
    ['gnome-terminal'],
    ['qterminal'],
    ['lxterminal'], # no search
)
