#! /usr/bin/env python3

import sys
import os

from lib.run_program import run_program

HERE = os.path.dirname(__file__)

if not os.path.isfile(os.path.join(HERE, 'NOT-AT-WORK')):
    sys.exit(0)

run_program(
    ['qbittorrent'], # make sure you select `Behaviour > Window state on startup: Hidden`
    ['transmission-gtk', '--minimized'],
    ['deluge'], # make it start minimised from the settings
    #['ionice', '-c', '3', 'qbittorrent'], # set start minimised from the settings
)
